name:                calc-server
version:             1.0.0.0
github:              "maxudd/calc-server"
license:             BSD-3-Clause
author:              "Maxim Gulak"
maintainer:          "gulakma@my.msu.ru"
copyright:           "2024 Maxim Gulak"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxudd/calc-server#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- servant
- warp 
- aeson
- text
- hspec
- hspec-wai
# - hspec-wai-json

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  calc-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calc-server

tests:
  calc-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calc-server
